### PR TITLE
chore: update go version to 1.19

### PR DESCRIPTION
**Pull request by deven0t**

### CODE REVIEW

**Comment by deven0t** [comment]
Hi @chen-keinan Please review this change :)
thanks

**Comment by chen-keinan** [comment]
@deven0t please check buid

**Comment by deven0t** [comment]
@chen-keinan yes, I updated the can you retrigger the build again. 
Thanks

**Comment by deven0t** [comment]
@chen-keinan , build is passed. can you approve and merge.
Thanks

**Review by chen-keinan — APPROVED** [review]

**Pull request merged**
